name: bonsai-preview
dependencies:
  - python=3.7
  - pip=19.1.1
  - jupyter=1.0.0
  - matplotlib=3.0.3
  - seaborn=0.9.0
  - plotly=3.10.0
  - scipy=1.3.0
  - pandas=0.25.1
  - numpy=1.16.4
  - pip:
      - microsoft-bonsai-api==0.1.2
      - bonsai-cli==1.0.4
      - azure-cli==2.5.1
      - azure-batch==9.0.0
      - cufflinks==0.16
      - vpython==7.6.0
      - pyglet==1.5.0
      - jinja2==2.11.2
      - python-dotenv==0.13.0
      - typer==0.2.1
      - applicationinsights==0.11.9
      - blobxfer==1.9.2
      - fire==0.2.1
      - beautifulsoup4==4.9.1
