name: bonsai-preview
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - matplotlib=3.0.3
  - pip=19.1.1
  - plotly=3.10.0
  - scipy=1.3.0
  - seaborn=0.9.0
  - pip:
      - azure-batch==9.0.0
      - azure-cli==2.12.1
      - beautifulsoup4==4.9.1
      - bitstring==3.1.7
      - blobxfer==1.9.2
      - bonsai-cli==1.0.5
      - cufflinks==0.16
      - fire==0.2.1
      - microsoft-bonsai-api==0.1.2
      - numpy==1.19.1
      - pandas==1.1.2
      - python-dotenv==0.13.0
      - rich==9.3.0
      - vpython==7.6.0
